Post association v5
open-education-api/specification pull request #175
Opened 2022-04-04 09:48 UTC by hamrt

This version has the earlier review information processed as well as a rebase to the v5 branch

2022-04-04 13:06 UTC, jelmerderonde commented
@hamrt kun je deze PR inschieten, maar dan mergen richting de v5 branch?

2022-04-06 15:00 UTC, jelmerderonde reviewed
@hamrt het ziet er goed uit, maar ik heb nog wat vragen om zeker te zijn dat ik het helemaal begrijp / het ermee eens ben.

Fijn als @hermanvand ook mee kijkt.

2022-04-07 14:09 UTC, hermanvand commented on v5/paths/AssociationInstanceMe.yaml
> +  description: POST a single association (enroll a person based on person information obtained from .wellknown endpoint and offering object)
Ik denk dat ook voor 'intern' gebruik een POST op een association geschikt is. Association is een resource op zichzelf met eigen attributen die je in de POST wilt meegeven, zoals de state. Ik zou het gek vinden om dat via een offering te doen.

2022-04-07 14:21 UTC, hermanvand commented on v5/paths/AssociationInstanceMe.yaml
> +              $ref: '../schemas/Offering.yaml'
Ik zou hier naast de offering ook course / program informatie verwachten. Of is dit een ofering 'expanded' met die info?

2022-04-07 14:21 UTC, hermanvand commented on v5/paths/PersonInstance.yaml
> +post:
Deze hebben we al eerder besproken. Het lijkt erop dat POST persons er niet is, omdat CACI dit oplost met een POST naar een osiris call. In het ontwerp is dit wel een OOAPI call. Voor het geval het SIS ooapi kan gerbuiken om een gaststudent toe te voegen. CACI wil hier ook wel naar toe in de toekomst. Leiden/Usis, zou dit wel eens kunnen gaan doen bijvoorbeeld.

2022-04-07 14:21 UTC, hermanvand commented on v5/schemas/PostResponse.yaml
> +  message:
Ja, voor het teruggeven van de 'beoordeling' van de thuisinstelling.

Na een POST /associations/me kan de thuisinstelling de state op pending zetten, omdat er nog een beoordeling moet plaatsvinden. In deze message komt daar informatie over te staan, waarmee de gastinstelling dan de student beter kan informeren.

2022-04-08 07:37 UTC, hamrt commented on v5/paths/AssociationInstanceMe.yaml
> +      - my_association_write
Ik dacht laten we een kleine scope nemen voor nu. Maar je zou er ook voor kunnen kiezen om hem algemener te noemen
we zouden ook gebruik kunnen maken van best practices van oAuth https://curity.io/resources/learn/scope-best-practices/
dat brengt ons dan in dit geval tot associations:me.write
Ik kan dat nog mee nemen in een volgende commit

2022-04-19 08:32 UTC, hermanvand requested changes

2022-04-19 08:32 UTC, hermanvand commented on v5/enumerations/resultState.yaml
> +  - queued
Hoi Ronald,

Top dat je deze mee wilt nemen, maar de wens is om deze 'queued' toe te voegen aan de associationState.yaml. Niet hier.

2022-04-19 12:20 UTC, jelmerderonde requested changes
Ha @hamrt,

Ziet er goed uit volgens mij. Nog een paar kleine dingetjes maar we zijn heel dichtbij zo:

- @hermanvand had nog een puntje over de `associationState` die elder thuis hoorde.
- Ik zie hier en daar nog wel wat attributen in de post bodies terugkomen waarvan ik me afvraag of die er thuishoren. Als een (externe) client een POST doet verwacht ik dat de request body een vrij "plat" object kan zijn en dat er niet heel veel geneste objecten bij horen te zitten. Mogelijk betekent dat dat we de attributen van offerings en associations nog over wat meer files moeten splitsen, zodat we nog iets selectiever kunnen zijn in de attributen die nodig zijn bij een POST.
- Ik twijfel nog het meest over de `POST /associations/external`. De enige usecase die ik kan bedenken is die van de LDE, waarbij er minors zijn waar naast de penvoerder (gastinstelling) en de thuisinstelling, nog meer instellingen bij betrokken zijn die ook op de hoogte moeten zijn van de inschrijving. Is deze daarvoor bedoelt?

Thanks voor het vele werk aan deze PR, dit is echt een flinke!

2022-04-19 12:20 UTC, jelmerderonde commented on v5/paths/AssociationInstanceExternal.yaml
> +  summary: POST /associations/external
De tabel is heel nuttig om te begrijpen welke opties er allemaal zijn.

Dit is dus het meest generieke endpoint: hiermee kan je een nog niet bekende student inschrijven op een offering die ook nog niet bekend is. Hebben we daar een usecase voor?

Verder vraag ik me af of je dan niet "uitgeklede" versies van de objecten wil hebben. Heb je hier bijv. bij de offering die aangeleverd wordt echt:
- `room`
- `component`
- `organization`
- etc

nodig?

2022-04-19 12:20 UTC, jelmerderonde commented on v5/paths/AssociationInstanceExternalMe.yaml
> +            associationItem:
Is de `associationType` hier niet dubbelop?

2022-04-19 12:20 UTC, jelmerderonde commented on v5/paths/AssociationInstanceMe.yaml
> +  description: POST a single association enroll a person based on person information obtained from .wellknown endpoint and an offering. The offering can either be identified by an offeringId if known
Wat bedoel je precies met `.wellknown` hier? De person wordt geacht bekend te zijn door middel van het  meegeleverde token. Maar hoe dat precies werkt kan verschillen per authenticatie / autorisatie mechanisme toch? 

In het geval van Studentmobiliteit wordt men geacht een `introspect` call te doen.

2022-04-19 14:21 UTC, hamrt commented
> Hoi Ronald,

Top dat je deze mee wilt nemen, maar de wens is om deze 'queued' toe te voegen aan de associationState.yaml. Niet hier. 

OK Fixed

2022-04-19 14:25 UTC, hamrt commented on v5/paths/AssociationInstanceExternal.yaml
> +  summary: POST /associations/external
Dat is natuurlijk het mooie aan deze oplossing je HOEFT ze niet door te geven ze zijn namelijk niet verplicht. Je kunt ze wel doornemen. Voor de koppeling zoals OSIRS die nu gebruikt lijkt het er op dat een aantal van die waardes wel doorgegeven moeten worden om zo uiteindelijk de gebruiker op de goede plek te laten landen

2022-04-19 14:36 UTC, hamrt commented on v5/paths/AssociationInstanceExternalMe.yaml
> +            associationItem:
Je bedoeld omdat je ook de type meekrijgt op basis van het type element in het offerings object? Beide velden zijn wel verplicht (voor de GET). In principe zou je ze uitelkaar kunnen halen. Van de andere kant ga je dan ook weer objecten "uitkleden". Wat heeft hier voorkeur? Data minimalistatie of structuur hergebruik?

2022-04-19 14:43 UTC, hamrt commented on v5/paths/AssociationInstanceMe.yaml
> +  description: POST a single association enroll a person based on person information obtained from .wellknown endpoint and an offering. The offering can either be identified by an offeringId if known
De persoon informatie wordt inderdaad via introspect opgehaald. Als het goed is is de metadata over het gebruik van de introspect en andere configuratie data beschreven in het .wellknown object? Hier kun je ook zien welke attributen en scopes terug kunnen komen. het is conform de schrijfwijze van swagger: https://swagger.io/docs/specification/authentication/openid-connect-discovery/#:~:text=%23%201)%20Define%20the,known/openid%2Dconfiguration

2022-04-19 15:30 UTC, hermanvand approved these changes

2022-04-22 15:29 UTC, jelmerderonde approved these changes

2022-04-23 06:38 UTC, merged