rename type parameters and attributes
open-education-api/specification pull request #179
Opened 2022-04-05 15:56 UTC by hermanvand

update type attributes according to #168

2022-04-06 07:56 UTC, jelmerderonde requested changes
Ha Herman, 

Je hebt ze bijna allemaal maar bent er een paar vergeten:
- addressType / postalType
- In paths/RoomCollection the type parameter
- Onderaan in spec.yaml staan een aantal voorbeelden handmatig uitgeschreven in json, ook daarin komen helaas types voor.

Dat was em!

2022-04-12 09:11 UTC, hermanvand commented
De wijzigingen zijn doorgevoerd. Ik heb gekozen om 'postalType' te hernoemen naar AddressType. Dat maakt het wat consequenter. Nu is ieder type attribuut vernoemd naar de resource.

2022-04-19 08:50 UTC, jelmerderonde approved these changes

2022-04-19 08:50 UTC, jelmerderonde commented
@hermanvand prima zo wat mij betreft. Pak jij het mergen verder op?

2022-04-19 15:00 UTC, merged