add group api
open-education-api/specification pull request #180
Opened 2022-04-05 20:17 UTC by hermanvand

all things related to groups are added

2022-04-06 07:21 UTC, jelmerderonde commented on v5/changed.md
> +## [unreleased]
Er is ook een Changelog.md in de root directory. Mogelijk kunnen we daar ook nog iets bij zetten over deze functionaliteit.

Ik vind de uitleg verder nog wat spaarzaam, misschien kun je nog iets toevoegen (bijv. onderaan in spec.yaml, waar de rest van de documentatie staat) over wat groepen precies zijn en waarvoor ze bedoeld zijn.

2022-04-06 07:22 UTC, jelmerderonde commented on v5/enumerations/groupType.yaml
> +  - learning group: A collection of participants carrying out common learning activities (definition from HORA)
HORA is een NL term en we mikken er met OOAPI toch een beetje op om internationaal te blijven. Misschien werkt HORA als term hier verwarrend? Wat denk jij?

2022-04-06 07:22 UTC, jelmerderonde commented on v5/enumerations/groupType.yaml
> +  - team: A collection of participants
Is een team niet generieker? Een collection of persons?

2022-04-06 07:25 UTC, jelmerderonde commented on v5/paths/GroupCollection.yaml
> +    - $ref: '../parameters/search.yaml'
Deze past niet helemaal lekker hier. De `q` paramater heeft als omschrijving:

> Filter by items having a name, abbreviation or description containing the given search term (exact partial match, case insensitive)

Maar groepen hebben geen abbreviation... Wat denk jij Herman?

2022-04-06 07:30 UTC, jelmerderonde commented on v5/paths/GroupPersonCollection.yaml
> +    '404':
Collections kunnen geen 404 als response hebben.

2022-04-06 07:31 UTC, jelmerderonde commented on v5/paths/OfferingGroupCollection.yaml
> +    '404':
Idem

2022-04-06 07:32 UTC, jelmerderonde commented on v5/paths/OrganizationGroupCollection.yaml
> +    '404':
Idem

2022-04-06 07:32 UTC, jelmerderonde commented on v5/paths/PersonGroupCollection.yaml
> +    '404':
En ook hier

2022-04-06 07:34 UTC, jelmerderonde commented on v5/paths/GroupCollection.yaml
> +get:
Ik mis denk ik bij alle collection responses het `ext` attribuut.

2022-04-06 07:35 UTC, jelmerderonde requested changes
@hermanvand, ziet er al goed uit! ik heb nog wel wat opmerkingen, hopelijk kun je daar nog wat mee :-).

2022-04-06 12:07 UTC, hermanvand commented on v5/changed.md
> +## [unreleased]
Ik dacht dat de changelog in de root directory ingevuld gaat worden op het moment dat we v5 releasen, dat dat een soort van samenvatting zou zijn ofzo. Anders snap ik niet helemaal waarom er 2 change files zijn.

En ja, ik zal een stukje uitleg toevoegen, goed punt!

2022-04-06 12:08 UTC, hermanvand commented on v5/enumerations/groupType.yaml
> +  - learning group: A collection of participants carrying out common learning activities (definition from HORA)
Ik had er erbij gezet om te laten zien dat we niet zelf deze indeling hebben verzonnen, maar ik zal dit gewoon weghalen, is niet heel relevant.

2022-04-06 12:08 UTC, hermanvand commented on v5/enumerations/groupType.yaml
> +  - team: A collection of participants
ja, klopt, ik zal daar expliciet bij zetten dat het studenten en docenten kunnen zijn.

2022-04-06 12:12 UTC, hermanvand commented on v5/paths/GroupPersonCollection.yaml
> +    '404':
Ja, dat dacht ik eerst ook en dat klopt deels
- /groups als collection kan geen 404 hebben
- maar /groups/{ID}/persons of /organizations/{ID}/groups etc. kan dat wel, want het {ID} kan dan niet gevonden worden

Ik heb daar dus onderscheid in gemaakt, dat klopt dan toch wel?

2022-04-06 13:59 UTC, jelmerderonde commented on v5/changed.md
> +## [unreleased]
Ja het is mij eerlijk gezegd ook niet helemaal duidelijk waarom we twee files hebben. Ik zet alles gelijk in de Changelog.md file in de root. Misschien weet @hamrt raad?

2022-04-06 14:01 UTC, jelmerderonde commented on v5/paths/GroupPersonCollection.yaml
> +    '404':
Hm goed punt. Mogelijk heb je gelijk, ben benieuwd wat @ruttromp hiervan vindt, want als we het zo bekijken heb ik ook nog wat werk aan een andere PR te verrichten.

2022-04-07 10:12 UTC, ruttromp commented on v5/paths/GroupPersonCollection.yaml
> +    '404':
@jelmerderonde een terechte opmerking. In de situaties die @hermanvand noemt is een 404 error logisch

2022-04-08 07:26 UTC, hamrt commented on v5/changed.md
> +## [unreleased]
1 changelog.md lijkt mij ook prima.

2022-04-08 14:43 UTC, jelmerderonde commented
@hermanvand het zou mooi zijn als we deze vlak voor of net na het mergen gelijktrekken met een aantal aanpassingen die gedaan zijn in alle andere calls:
- Error responses toevoegen, zie #174 
- Afhankelijk van de keuze die gemaakt wordt over `sourcedId` of `primaryId`, kunnen we dat ook in deze PR nog gelijktrekken.

2022-04-12 09:28 UTC, hermanvand commented on v5/changed.md
> +## [unreleased]
Dan gebruik ik de root, changelog.md

2022-04-12 09:57 UTC, hermanvand commented on v5/changed.md
> +## [unreleased]
Ik heb uitleg toegevoegd bij de resource zelf. Onderaan de pagina vind ik niet een goede plek, omdat daar uitleg staat van dingen die over alle/meerdere resources gaan. Wel denk ik dat het slim is nog wat uitgebreidere uitleg te maken op de wiki. Maar dat geldt niet alleen voor groepen. Dat zouden we voor meerdere resources kunnen doen.

2022-04-12 10:25 UTC, hermanvand commented
Hoi Jelmer, ik heb de issues uit de review opgelost, maar nog niet de error responses toegevoegd. Want ik heb die error schema's niet in deze branch zitten. Laat maar weten als deze gemerged is, dan maak ik een nieuw pull request om de error messages gelijk te trekken.

2022-04-19 11:19 UTC, jelmerderonde approved these changes

2022-04-19 11:20 UTC, jelmerderonde commented
@hermanvand ziet er goed uit, ik ga deze mergen!

2022-04-19 11:20 UTC, merged