Multilingual responses for M2M requests #163
open-education-api/specification pull request #187
Opened 2022-04-07 19:11 UTC by mpdejong

Based on the IMS Edu-API solution for multiple language values, I have coded an example with the use of `LanguageTypedString`. This makes it possible to have multiple values of attributes in one record.

The attributes that need the option of different values by language need to use `LanguageTypedString` instead of `string`.

2022-04-08 05:29 UTC, jelmerderonde requested changes
@mpdejong dank voor deze aanzet! Dit lijkt me inderdaad hoe we het moeten gaan oplossen. 

Het moet nog wel wat anders in elkaar gezet worden, laten we straks tijdens het overleg even bepalen wie dat gaat doen.

2022-04-08 05:29 UTC, jelmerderonde commented on v4/schemas/Program.yaml
> +      "$ref": "#/$defs/LanguageTypedString"
Deze verwijzing moeten we nog wel ergens definiëren. Ik denk zelf in iets als `/v5/schemas/LanguageString.yaml`.

2022-04-08 05:29 UTC, jelmerderonde commented on v4/schemas/Program.yaml
> +    "$comment": 'Origin: LanguageTypedString (Unordered); A String with an associated language code.'
Die beschrijving kan dan ook opgenomen worden in `/v5/schemas/LanguageString.yaml`.

2022-04-08 15:04 UTC, jelmerderonde commented
Nog twee extra vragen voor wie hier verder mee gaat:
* Wat doen we met Content-Negotiation als er allemaal multi-language strings komen?
* Is er nog behoefte aan een query parameter waarmee je als client een voorkeurstaal kunt opgeven en dan alleen die terugkrijgt? Wellicht een beetje overkill, maar het zou kunnen.

2022-04-11 14:32 UTC, ruttromp commented on v4/schemas/Program.yaml
> +    "$comment": 'Origin: LanguageTypedString (Unordered); A String with an associated language code.'
@mpdejong  deze wijziging zit in de /v4 folder in plaats van /v5

2022-04-15 09:10 UTC, ruttromp commented
Vervangen door #192

2022-04-15 09:10 UTC, closed without merging