Modify time-related attributes in Educations and EducationOfferings
open-education-api/specification pull request #189
Opened 2022-04-08 16:01 UTC by jelmerderonde

This PR provides a fix for #154 and also addresses some isssues of #106:

- Adds attribute `firstStartDate` to Program.
- Adds the attribute `duration` to Course and Component.
- Adds `enrollStartDate` and `enrollEndDate` to ProgramOffering and CourseOffering.
- Adds `flexibleEntryPeriodStart` and `flexibleEntryPeriodEnd` to ProgramOffering and CourseOffering. These two attributes can be used instead of a `startDate` to signify a Program or Course wherein a student can start at various moments with the offering, without missing anything.
- Rename the `lengthOfProgram` attribute to `duration` and change the format to duration as described in RFC 3339.
- Made `endDate` (ProgramOffering and CourseOffering) and `endDateTime` (ComponentOffering) optional attributes instead of required. This is because of the addition of the flexible start / end date(times), which makes it possible to also have offerings which have flexible starting or ending dates.

2022-04-08 16:04 UTC, jelmerderonde commented
@hermanvand en @hamrt willen jullie allebei een blik op deze PR werpen?

Ik twijfel met name nog over de `flexibleEntryPeriodStart` en `flexibleEntryPeriodEnd` attributen. Ik heb die toegevoegd voor compatibiliteit met RIO. Daar kent een AangebodenOpleidingCohort een attribuut `beginInstroomperiode`:

> De eerste dag dat een student in een cohort van een aangebodenopleiding met een flexibele instroom kan beginnen. Studenten kunnen ook later beginnen. De opleiding start op het moment dat de leerling begint en deze mist daardoor niets van de opleiding.

En een attribuut `eindelnstroomperiode`:

> De laatste dag dat een student kan beginnen in een cohort van een aangeboden opleiding met een flexibele instroom. Studenten kunnen niet later dan deze datum aan dit cohort van deze aangeboden opleiding beginnen.

Op zich ok, maar het zorgt er voor dat de reguliere `startDate` niet langer verplicht kan zijn en ik weet niet of we dat wenselijk vinden.

2022-04-08 16:06 UTC, jelmerderonde commented
Verder heb ik ook de keuze gemaakt om ComponentOffering ongewijzigd te laten, omdat ik de nieuwe attributen daar toch niet zo op hun plaats vond.

2022-04-11 15:07 UTC, hamrt requested changes

2022-04-12 12:11 UTC, hermanvand commented on v5/schemas/ProgramOffering.yaml
>        - endDate
Het 'probleem' met start & enddate lijkt mij iets genuanceerder te zijn. 
- Een startdate & enddate van een offering geven het begin en einde van de offering aan
- Een flexibleEntryPeriodStart en flexibleEntryPeriodEnd, zeggen alleen iets over de start periode waarin de student kan beginnen. Dit zegt dus niets over de enddate.

In de tijd lijkt dit dan de volgorde, 
- een offering begint op startDate
- dan is er eventueel een flexibele entry periode van flexibleEntryPeriodStart tot flexibleEntryPeriodEnd
- de offering eindigt op endDate

Volgens mij kunnen we nog steeds prima zeggen dat startDate & endDate beiden verplicht zijn. Optioneel is er een flexibele entry periode. Die hoogstwaarschijnlijk begint op startDate. Je zou je dus kunnen afvragen of je niet met alleen een optionele flexibeleEntryPeriodEnd af kan om de entry periode aan te geven, maar dat is minder belangrijk.

2022-04-19 08:48 UTC, jelmerderonde commented on v5/schemas/ProgramOffering.yaml
>        - endDate
Hm goed punt, @hermanvand, ik denk dat ik wel mee kan gaan in jouw redenering.

@hamrt eens? Zo ja, dan pas ik de PR als volgt aan:
- `startDate` weer verplicht maken.
- Iets meer documentatie om dit inzichtelijk te maken.

2022-04-19 11:12 UTC, jelmerderonde commented
@hamrt en @hermanvand ik heb de PR aangepast. Als een van jullie nog een laatste check kan doen, dan kan ik deze mergen.

2022-04-19 15:02 UTC, hamrt approved these changes
volgens mij prima

2022-04-19 17:32 UTC, merged