#157 Adding otherCodes to Program schema
open-education-api/specification pull request #190
Opened 2022-04-12 09:33 UTC by ruttromp

#157 kan op deze manier worden opgelost.

Ik ben niet 100% zeker van deze oplossing, daarom een aantal opmerkingen voor de reviewers:
- het attribuut `otherCodes` wordt ook binnen eduAPI gebruikt op vergelijkbare wijze
- deze oplossing is generiek en laat relatief veel vrijheid aan de gebruiker
- dit zou ook in `ext` kunnen, maar dan is er in zijn geheel geen structuur
- mijn advies is om te onderzoeken of het mogelijk is om de key:value lijst te normaliseren, bijvoorbeeld in een separate git repository

2022-04-12 12:32 UTC, hermanvand commented on v5/schemas/Program.yaml
> +  otherCodes:
Ik denk dat otherCodes wel waarde heeft ten opzichte van ext, omdat het aangeeft dat er meerdere codes zijn waarmee het object te identificeren is. Ik heb wel een paar vragen.

- otherCodes impliceert dat er ook een specifieke 'code' is. Ik heb wel eens primaryCode zien langskomen. Komt die ook? Maar zelf zou ik liever in programs een programCode opnemen (net zoals programId & programType). Dit zou ik in ieder geval dan ook in dit PR meenemen.
- otherCodes impliceert voor mij ook dat alle andere codes hierin moeten. Dan kun je dus van programs de crohoCode en creboCode opnemen.
- ik vind het wel moeilijk te bepalen wat een 'code' is, waar is de grens? Ik twijfel bijvoorbeeld  over de fieldsOfstudy (isced). Dat is toch ook een code?
- In het kader van studentmobiliteit zou ik overwegen om hier ook het thema in te zetten van een program/course. Dat is van hetzelfde niveau als croho en isced. Past dat in het idee van deze aanpassing?

2022-04-14 11:11 UTC, hamrt requested changes
ik zou dit dus op pakken door een extra file mee te nemen otherCodes.yaml met daarin dan de key value oplossing die nu onder additional poprties zit

2022-04-15 10:10 UTC, ruttromp commented
Aanpassingen:

- generiek otherCode schema toegevoegd 
- array met referentie naar otherCode toegevoegd in  Program
- crohoCreboCode verwijderd uit Program (dit kan nu in otherCode)
- in lijn met eduAPI specificatie de primaryCode toegevoegd aan Program

To-do:
- besluit over primaryCode, is dit wenselijk? (@jelmerderonde @hamrt @hermanvand)
- op welke plaatsen is een verwijzing naar het generieke schema `otherCode` nodig? En idem voor primaryCode (@hamrt)
- doorvoeren finale wijzigingen (@ruttromp)

2022-04-18 23:17 UTC, hamrt commented
endpoints waarop ik meerdere id's zou verwachten:
persons, 
educationspecifications, programs, courses, components,
associations,
programofferings, courseofferings, componentofferings,
groups,
organziations.

2022-04-19 08:45 UTC, jelmerderonde commented
@ruttromp eduAPI beschrijft het attribuut `primaryCode` als volgt:

> The primary human readable identifier for the entity. This will often take the form of a human readable code as defined by the institution or region

Op basis daarvan denk ik dat het wel wenselijk is om het attribuut expliciet ook in de OOAPI op te nemen. We weten immers dat instellingen meestal ook een eigen primaire code (of iets vergelijkbaars) kennen voor hun entiteiten.

2022-04-19 09:45 UTC, jelmerderonde commented
Maybe also add these new attributes to:
- Buildings
- Rooms

2022-04-20 07:01 UTC, ruttromp commented
@jelmerderonde en @hamrt de besproken aanpassingen zijn gedaan, uiteindelijk nog een flinke set wijzigingen.

Vraag: is de query parameter voor `primaryCode` zo in orde? heb deze alleen op de 'single instance' endpoints toegevoegd

2022-04-22 07:14 UTC, jelmerderonde requested changes
@ruttromp ik krijg de documentatie van deze branch niet gerenderd, ergens zit er een foutje in je aanpassingen waardoor het niet meer werkt.

Belangrijkste punt van feedback is dat de query parameter thuishoort op de collection endpoints, niet op de single instances:
- Om een single instance op te vragen heeft een afnemer de UUID nodig. Er is dus in zo'n geval niet meer te filteren op de `primaryCode`.
- Bij collections werkt het juist weer wel, als er een entiteit met de gevraagde `primaryCode` bestaat, kan de afnemer een resultaat verwachten met een array met één object.

Als je wilt kan ik later vandaag er nog induiken om te kijken waar de fout ontstaan is. Laat maar weten.

2022-04-22 11:05 UTC, ruttromp commented
Aangepast. @jelmerderonde wil jij deze opnieuw reviewen (en aanpassen+mergen) indien nodig?

2022-04-22 12:20 UTC, jelmerderonde approved these changes

2022-04-22 12:23 UTC, merged