EducationSpecification
open-education-api/specification pull request #193
Opened 2022-04-18 22:47 UTC by hamrt

solution for ILO discussion

2022-04-19 13:57 UTC, jelmerderonde reviewed
@hamrt goede eerste voorzet zo! Bijgaand mijn eerste feedback. Ik weet dat jij er ook nog mee bezig bent, dus ik ga er zeker nog een keer naar kijken deze dagen.

Mijn belangrijkste vraagstuk (en ik heb het antwoord zelf niet) is in hoeverre we dit ding heel RIO-specifiek willen maken, of juist niet. Als we het niet te RIO specifiek willen hebben, maar ook enige waarde in zichzelf willen laten hebben, dan kunnen we de RIO-specifieke attributen eruit laten en die opnemen in het consumer object.

En, ohjee, ik twijfel nog steeds een beetje of we het niet beter in Programs en Courses zelf hadden kunnen verwerken.

Dan had het als volgt gekund:
- Aantal attributen toevoegen aan Program en Course
- Een verplicht boolean attribuut `offerable` (geeft aan of iets paars of geel is)
- Een optioneel attribuut `offeringFor` waarmee je kunt verwijzen naar het ding in het geel
- Convenience endpoints zoals `GET /offerablePrograms` en `GET /offerableCourses`.

Ergens toch ook nog een oplossing waar ik van gecharmeerd blijf.

2022-04-19 13:57 UTC, jelmerderonde commented on v5/paths/EducationSpecificationInstance.yaml
> +  summary: GET /educationspecification/{educationspecificationId}
Ik weet eigenlijk niet wat hier de norm is:

`/educationSpecification`
of
`/educationspecification`

Dus moet dit met hoofdletter of niet?

2022-04-19 13:57 UTC, jelmerderonde commented on v5/paths/EducationSpecificationInstance.yaml
> +  summary: GET /educationspecification/{educationspecificationId}
Willen we ook een call om alle educationSpecifications op te vragen? dus `/educationSpecifications`?

2022-04-19 13:57 UTC, jelmerderonde commented on v5/enumerations/controlingEntity.yaml
> +  The entity contoling this education. The type of entity that certifies this education.
controlling is met twee l's :-)

2022-04-19 13:57 UTC, jelmerderonde commented on v5/enumerations/controlingEntity.yaml
> +    - instituition: INSTELLING
spelfoutje

2022-04-19 13:57 UTC, jelmerderonde commented on v5/enumerations/educationSpecificationSubType.yaml
> +enum:
Dit is dan een niet-verplicht veld neem ik aan? Want iets kan een minor of een module zijn dacht ik. 

Of moet minor hierbij als optie?

2022-04-19 13:57 UTC, jelmerderonde commented on v5/enumerations/educationSpecificationType.yaml
> +  The type of education specification
Dit wordt heel erg RIO-specifiek.

Ik worstel nog een beetje of we dit niet wat generieker willen houden. Dat zou betekenen dat we dit attribuut ook onderdeel kunnen laten zijn van het RIO consumer object.

Wat denk jij?

2022-04-19 13:57 UTC, jelmerderonde commented on v5/schemas/EducationSpecification.yaml
> +  startDate:
Mogelijk `startDate` dus hieruit halen zoals vanochtend besproken.

2022-04-19 13:57 UTC, jelmerderonde commented on v5/schemas/EducationSpecification.yaml
> +  endDate:
Idem

2022-04-19 13:57 UTC, jelmerderonde commented on v5/schemas/EducationSpecification.yaml
> +  formalDocument:
Is dit niet hetzelfde als `qualificationAwarded`? Of haal ik nu dingen door elkaar?

2022-04-19 13:57 UTC, jelmerderonde commented on v5/schemas/EducationSpecification.yaml
> +  educationSpecificationCode:
Ik denk niet dat dit hier thuishoort. De OnderwijsEenheidCode moet denk ik gewoon in het RIO consumer object. We zouden hier nog wel de `primaryCode` en `otherCodes` velden toe kunnen voegen.

2022-04-19 13:57 UTC, jelmerderonde commented on v5/schemas/studyLoadDescriptor.yaml
> +type: object
Nuttig object dit. Zouden we dit niet ook bij de andere objecten (Program / Course / Component) op die manier moeten toepassen?

2022-04-19 20:32 UTC, hamrt commented on v5/paths/EducationSpecificationInstance.yaml
> +  summary: GET /educationspecification/{educationspecificationId}
het is nog erger... het moet eigenlijk zijn education-specifications analoog aan academic-sessions en news-items

2022-04-19 20:37 UTC, hamrt commented on v5/schemas/EducationSpecification.yaml
> +  startDate:
done

2022-04-19 20:37 UTC, hamrt commented on v5/schemas/EducationSpecification.yaml
> +  endDate:
done

2022-04-19 20:38 UTC, hamrt commented on v5/schemas/EducationSpecification.yaml
> +  formalDocument:
ja nu haal je dingen door elkaar qualification awarded geeft aan wat voor soort diploma je krijgt en niet wat het waardedocument soort is

2022-04-19 20:55 UTC, hamrt commented on v5/schemas/EducationSpecification.yaml
> +  educationSpecificationCode:
opgelost met otherCode

2022-04-19 21:09 UTC, hamrt commented on v5/paths/EducationSpecificationInstance.yaml
> +  summary: GET /educationspecification/{educationspecificationId}
dat is een optie. De vraag is natuurlijk in hoeverre we langs die route vaak zaken op gaan vragen. Van de andere kant zorgt het er wel weer voor dt de endpoints redelijk vergelijkbaar blijven. Ik zal hem zo opnemen.

2022-04-19 21:23 UTC, hamrt commented on v5/schemas/studyLoadDescriptor.yaml
> +type: object
lijkt me handig om te doen even voor nu op de backlog zetten als we deze PR afgerond hebben kunnen we die andere aanpassingen ook doen anders wordt deze wel heel druk

2022-04-22 07:28 UTC, jelmerderonde requested changes
Ha Ronald,

Nog wat punten van feedback:
- Ik mis nog een manier om makkelijk alle "onderliggende" Courses of Programs op te vragen die bij een EducationalSpecification horen. Misschien moeten we nog de paden `/educational-specification/{uuid}/programs` en `/educational-specification/{uuid}/courses`  toevoegen?

Laten we zo tijdens het overleg nog even bespreken hoet wel/niet RIO-specifiek we dit willen maken.

2022-04-22 07:28 UTC, jelmerderonde commented on v5/paths/EducationSpecificationCollection.yaml
> +    - name: Type
dit moet met een kleine letter t zijn: `type`

2022-04-22 07:28 UTC, jelmerderonde commented on v5/paths/EducationSpecificationCollection.yaml
> +    - name: Primarycode
moet zijn: `primaryCode`

2022-04-22 07:28 UTC, jelmerderonde commented on v5/paths/EducationSpecificationCollection.yaml
> +    - name: ControllingEntity
Moet zijn: `controllingEntity`

2022-04-22 07:28 UTC, jelmerderonde commented on v5/schemas/EducationSpecificationProperties.yaml
> +  - controlingEntity
`controllingEntity` is met twee l's

2022-04-22 07:28 UTC, jelmerderonde commented on v5/schemas/EducationSpecificationProperties.yaml
> +  otherCode:
is dit niet `otherCodes`?

2022-04-22 07:51 UTC, hamrt commented on v5/paths/EducationSpecificationCollection.yaml
> +    - name: Type
fixed

2022-04-22 07:51 UTC, hamrt commented on v5/paths/EducationSpecificationCollection.yaml
> +    - name: Primarycode
fixed

2022-04-22 07:51 UTC, hamrt commented on v5/paths/EducationSpecificationCollection.yaml
> +    - name: ControllingEntity
fixed

2022-04-23 07:18 UTC, jelmerderonde approved these changes

2022-04-23 07:20 UTC, merged