Updates education specification association
open-education-api/specification pull request #216
Opened 2022-05-11 19:46 UTC by hamrt

updates:

1. EducationSpecification subtype verwijderd en toegevoegd aan consumer
2. Aanpassing op associations:
   - PUT ipv POST op associations/{id} 
   - expanded en expandable schemas toegevoegd om leesbaarheid te verbeteren in redoc op de volgende endpoints:  associations/{id} (results) offerings/{id}/associations (results)

3. aanpassing en include van README.md in HOME.md van documentatie site

2022-05-16 09:38 UTC, ruttromp commented on v5-beta/consumers/RIO/V1/EducationSpecification.yaml
> +      - OPLEIDING
de optie OPLEIDING is een vreemde eend. Is het mogelijk om dit in het Engels te specificeren?

2022-05-16 09:45 UTC, ruttromp commented on v5-beta/paths/OfferingAssociationCollection.yaml
> +                #   - items
Uitgecommentarieerde regels opschonen?

2022-05-16 09:47 UTC, ruttromp commented on v5-beta/schemas/CourseOfferingAssociationExpanded.yaml
> +        $ref: './Offering.yaml'
No newline at end of file

2022-05-17 08:31 UTC, jelmerderonde requested changes
Ha Ronald, het ziet er op zich goed uit, maar ik dacht dat we bedacht hadden om altijd de properties van association op hoofdniveau terug te laten komen?

`POST /associations/me` zou dan bijv worden:

```json
{
  "associationType": "componentOfferingAssociation",
  "role": "student",
  "state": "associated",
  "ext": {},
  "offering": "123e4567-e89b-12d3-a456-134564174000"
}
```

Stuk simpeler dan dat het nu is. Maar weet niet zeker of dit mogelijk is.

2022-05-30 15:41 UTC, hamrt commented on v5-beta/consumers/RIO/V1/EducationSpecification.yaml
> +      - OPLEIDING
fixed

2022-06-01 07:17 UTC, jelmerderonde commented
@hamrt ik ga zo nog even goed naar de code kijken, maar mijn eerste gedachte is om het resultaat van de PATCH altijd hetzelfde te laten zijn. Dus even kijken welke responsattributen beide functionaliteiten nodig hebben en die combineren tot één respons die altijd gevolgd wordt.

Als dat toch niet goed past zou een alternatief kunnen zijn om meerdere responsen te definieëren op de ene PATCH call.

2022-06-01 07:20 UTC, jelmerderonde commented
@hamrt ik snap alleen niet waarom de `POST /associations/external` niet nodig zou zijn. Dat is een call tussen twee OOAPI endpoints en moet straks ook gaan werken tussen bijv. Osiris en USIS en wel degelijk iets om te specificeren lijkt me...

2022-06-01 07:21 UTC, jelmerderonde commented on CHANGELOG.md
> +- PUT associations/{id} endpoint
Volgens mij hebben we geen PUTs meer, maar PATCH

2022-06-01 07:33 UTC, Marcel-Noordzij commented
Is het mogelijk om uit te leggen wat deze associations/external moet doen?
Ik wil graag meedenken, om te toetsen hoe dit gaat werken voor het LDE project, maar ik snap niet wat deze service doet

2022-06-01 07:42 UTC, jelmerderonde reviewed
Hoi Ronald,

Vast wat eerste feedback, maar laten we het vanmiddag verder bespreken:
- De oude PUT en POST calls moeten nog opgeruimd worden.
- Ik snap nog niet zo goed wat er gebeurd met de Expandable / Expanded schemas.

Verder wat opmerkingen in de code geplaatst.

2022-06-01 07:42 UTC, jelmerderonde commented on CHANGELOG.md
> +- PUT associations/{id} endpoint
Moet zijn `PATCH` denk ik

2022-06-01 07:42 UTC, jelmerderonde commented on v5-beta/consumers/RIO/V1/EducationSpecification.yaml
> +type: object
Goed om van deze consumer ook nog een example te maken in de examples subdirectory en daarnaar te verwijzen vanuit de `schemas/EducationSpecficiationProps.yaml` file.

2022-06-01 07:42 UTC, jelmerderonde commented on v5-beta/paths/AssociationInstance.yaml
> +              type: object
Is het mogelijk om de attributen van association direct onder de root te laten vallen?

2022-06-01 07:42 UTC, jelmerderonde commented on v5-beta/paths/AssociationInstance.yaml
> +                state:
Moet dit niet `remoteState` zijn?

2022-06-01 07:42 UTC, jelmerderonde commented on v5-beta/paths/AssociationInstanceExternal.yaml
> +            association:
Idem, kan dit naar het rootniveau getrokken worden?

2022-06-01 13:31 UTC, hamrt commented on v5-beta/paths/AssociationInstance.yaml
> +                state:
klopt en aangepast op basis van swimminglane

2022-06-01 13:42 UTC, hamrt commented on CHANGELOG.md
> +- PUT associations/{id} endpoint
klopt is aangepast en external is verwijderd

2022-06-01 13:49 UTC, hamrt commented on v5-beta/paths/AssociationInstance.yaml
> +              type: object
Ik kan deze lines niet meer terug vinden lijkt er op dat dit al gefixed is bij mij lokaal. Ik zal dit zo nog eens pushen voor de zekerheid

2022-06-01 13:49 UTC, hamrt commented on v5-beta/paths/AssociationInstanceExternal.yaml
> +            association:
idem

2022-06-02 17:14 UTC, jelmerderonde reviewed
Ha Ronald,

Ik was begonnen aan een uitgebreide review, maar heb uiteindelijk besloten zelf wat verder te werken aan je branch. Ik heb best wat zitten tweaken aan de POST en PATCH calls, maar vind het er zelf goed uitzien zo:

- Meeste `id`'s en `primaryCodes` readOnly gemaakt zodat je die als aanleverende partij niet hoeft mee te geven.
- Toplevel `association` object uit een request body gehaald
- `remoteState` writeOnly gemaakt
- Aan de verschillende offerings een optioneel `writeOnly` attribuut `program`, `course` of `component` toegevoegd zodat het met een POST mogelijk is om ook de details over de education meet te sturen. 
- Verder nog wat dingetjes rechtgetrokken in EducationSpecification

Ik twijfel verder heel erg of we de volgende calls er voor nu niet beter uit kunnen laten:
- `POST /associations/me`
- `POST /offerings/{offeringId}/associations/me`

Wat denk jij?

2022-06-02 18:36 UTC, hamrt commented on v5-beta/schemas/ProgramId.yaml
> +    readOnly: true
Zou ik hier niet doen is namelijk al een gesplitste ID als je hem nodig hebt haal je hem er bij of niet

2022-06-03 12:28 UTC, merged